(function () {
  const api = (window.BAT_CONFIG?.apiBase || '').replace(/\/$/, ''); let point = null;
  const loc = document.getElementById('loc'), submit = document.getElementById('submit'), issues = document.getElementById('issues');
  function esc(value) { return String(value || '').replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;', "'":'&#39;' }[c])); }
  async function load() { try { const res = await fetch(`${api}/api/civic/issues`); const list = await res.json(); if (!res.ok) throw new Error(list.error); issues.innerHTML = list.length ? list.map(x => `<article class="issue ${esc(x.status)}"><div><span class="pill">${esc(x.type.replace('_', ' '))}</span> <span class="pill">${esc(x.status.replace('_', ' '))}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><p class="note">${esc(x.area || 'Bangalore')} · ${new Date(x.created_at).toLocaleDateString()}</p>${x.action_note ? `<p><strong>Action update:</strong> ${esc(x.action_note)}</p>` : ''}</article>`).join('') : '<p>No civic issues have been reported yet.</p>'; } catch (e) { issues.textContent = e.message || 'Could not load civic issues.'; } }
  document.getElementById('locate').addEventListener('click', () => { if (!navigator.geolocation) return; loc.textContent = 'Locating…'; navigator.geolocation.getCurrentPosition(p => { point = { lat:p.coords.latitude, lng:p.coords.longitude }; loc.textContent = `Location ready (±${Math.round(p.coords.accuracy)}m)`; submit.disabled = false; }, () => loc.textContent = 'Location permission is needed to pin this issue.', { enableHighAccuracy:true, timeout:10000 }); });
  document.getElementById('issue-form').addEventListener('submit', async event => { event.preventDefault(); if (!point) return; submit.disabled = true; try { const session = await window.SupabaseAuthClient?.getSession?.(); if (!session?.access_token) { location.href = 'login.html?returnTo=civic.html'; return; } const body = { type:document.getElementById('type').value, title:document.getElementById('title').value, description:document.getElementById('description').value, area:document.getElementById('area').value, ...point }; const res = await fetch(`${api}/api/civic/issues`, { method:'POST', headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`}, body:JSON.stringify(body) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Submission failed'); event.target.reset(); point = null; loc.textContent = 'Thanks — safety signal submitted for review.'; await load(); } catch (e) { loc.textContent = e.message; } finally { submit.disabled = !point; } });
  document.getElementById('refresh').addEventListener('click', load); load();
})();
